name: Test Workflow

on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a script
        run: echo "This is the first workflow running on the main branch."

      - name: print variables
        run: date
  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a script
        run: "Get-Date -DisplayHint Date"
  job3:
    name: third Job
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a script
        run: date
  job4:
    name: Fourth Job
    needs: 
        - job1
        - job2
        - job3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Run a script
      #   run: "Get-ChildItem env: | Sort-Object Name | Format-Table -AutoSize"

      - name: Run a multi-line script
        uses: gavinswilson/update_readme_timestamp@main #from another repo